### ISSUE TITLE
Uppercase/Lowecase error, fails on live systems

### ISSUE THREAD

**Issue by EdwardLecock** [LCD344/kirby-mailer-wrapper#2]
https://github.com/LCD344/kirby-mailer-wrapper/blob/3a5d78ea2e571bb404329021793f8863189d8705/mailer.php#L10
and
https://github.com/LCD344/kirby-mailer-wrapper/blob/3a5d78ea2e571bb404329021793f8863189d8705/mailer.php#L15

both throw a fatal warning on live systems because the files are named helpers.php (not Helpers.php) and routers.php (not Routers.php)

**Comment by LCD344** [comment]
Merged, and so it should fix
